version: 0.2

phases:
  pre_build:
    commands:
      - echo prebuild
  build:
    commands:
      - yes | sudo apt-get update
      - yes | sudo apt-get install python3
      - python --version
      - pip install -r requirements.txt
  post_build:
    commands:
      - echo Build completed on `date`
