version: 0.2

phases:
  pre_build:
    commands:
      - echo prebuild
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 153432822124.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - sudo systemctl start docker
      - sudo systemctl enable docker
      - sudo systemctl status docker
      - docker -v
      - docker build -t onboarding-automation-ui .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 153432822124.ecr.ap-south-1.amazonaws.com/onboarding-automation-ui
